//
//  kirby.h
//  
//
//  Created by Mary Zhu on 12/5/18.
//

#ifndef kirby_h
#define kirby_h

#define GL_GREEN   0xFF00FF00
#define GL_CYAN    0xFF00FFFF
#define GL_MAGENTA 0xFFFF00FF

// kirby colors
#define GL_WHITE   0xFFFFFFFF
#define GL_BLACK   0xFF000000
#define GL_LIGHT_RED 0xEA3C53
#define GL_RED     0xFFFF0000
#define GL_LIGHT_PINK 0xFFB6C1
#define GL_PINK 0xFFC0CB
#define GL_DARK_PINK 0xDB7093
#define GL_HOT_PINK 0xFF1493

// ghost kirby colors
#define GL_DARK_BLUE    0xFF0000FF
#define GL_BLUE     0x1D8ECE
#define GL_PASTEL_BLUE  0x27AEE3
#define GL_LIGHT_BLUE   0xE3F2FD

// coin colors
#define GL_YELLOW  0xFFFFFF00
#define GL_AMBER   0xFFFFBF00
#define GL_ORANGE  0xFFA500

// gumba colors
#define GL_BROWN   0xB06A3B
#define GL_TAN     0xD2B48C

// brick colors
#define GL_DARK_BROWN 0x654321

//Proposed change: find a significantly more efficient way to draw Kirby than manually creating color maps

unsigned standing_kirby_right_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK,GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_DARK_PINK, GL_LIGHT_PINK, GL_RED, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK,GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_PINK, GL_BLACK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK,
    GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK,
    GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_PINK, GL_BLACK,
    GL_BLACK, GL_RED, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK,GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_RED, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_PINK, GL_PINK, GL_RED, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_HOT_PINK, GL_WHITE, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_DARK_PINK, GL_RED, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_BLACK,
    GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE
};

unsigned standing_kirby_left_map[] = {
    0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xffff0000, 0xdb7093, 0xdb7093, 0xffff0000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xffff0000, 0xffb6c1, 0xdb7093, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xff000000, 0xffff0000, 0xffb6c1, 0xff000000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff000000, 0xdb7093, 0xffb6c1, 0xff000000, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xff000000, 0xffffffff, 0xff000000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xff000000, 0xffc0cb, 0xffb6c1, 0xff000000, 0xffc0cb, 0xff1493, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xff000000, 0xff000000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff000000, 0xff000000, 0xffc0cb, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff000000, 0xff000000, 0xffff0000, 0xdb7093, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffff0000, 0xff000000, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xdb7093, 0xffff0000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xdb7093, 0xffff0000, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xdb7093, 0xff1493, 0xff1493, 0xff1493, 0xffffffff, 0xff1493, 0xff000000, 0xffffffff, 0xff000000, 0xffff0000, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xffff0000, 0xdb7093, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xdb7093, 0xffff0000, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xff000000, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff000000, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff000000, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff
};

unsigned walking_kirby_right_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_DARK_PINK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_HOT_PINK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_HOT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_HOT_PINK, GL_PINK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_LIGHT_PINK, GL_PINK, GL_DARK_PINK, GL_BLACK, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_PINK, GL_DARK_PINK, GL_BLACK,
    GL_BLACK, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_RED, GL_PINK, GL_BLACK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_RED, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_PINK, GL_BLACK,
    GL_BLACK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_HOT_PINK, GL_PINK, GL_PINK, GL_BLACK,
    GL_BLACK, GL_HOT_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_HOT_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_DARK_PINK, GL_WHITE, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_DARK_PINK, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_RED, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_RED, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_DARK_PINK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_DARK_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_DARK_PINK, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK, GL_BLACK, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK,GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE
};

unsigned walking_kirby_left_map[] = {
    // run reverseString on walking_kirby_right[]
    0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xdb7093, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xdb7093, 0xff1493, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffc0cb, 0xff1493, 0xdb7093, 0xffb6c1, 0xff1493, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff1493, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xdb7093, 0xffc0cb, 0xffb6c1, 0xff000000, 0xdb7093, 0xffb6c1, 0xff000000, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xdb7093, 0xff000000, 0xffffffff, 0xffffffff, 0xff000000, 0xdb7093, 0xffc0cb, 0xff1493, 0xffb6c1, 0xffb6c1, 0xff000000, 0xff1493, 0xffb6c1, 0xff000000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xdb7093, 0xff000000, 0xffffffff, 0xff000000, 0xffc0cb, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xffff0000, 0xff000000, 0xffc0cb, 0xffb6c1, 0xff000000, 0xffc0cb, 0xffff0000, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xff000000, 0xff000000, 0xffc0cb, 0xffc0cb, 0xff1493, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xff000000, 0xff000000, 0xff1493, 0xff1493, 0xff1493, 0xdb7093, 0xdb7093, 0xffff0000, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xff1493, 0xff000000, 0xffffffff, 0xff000000, 0xdb7093, 0xffff0000, 0xff1493, 0xff1493, 0xffffffff, 0xdb7093, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xff1493, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffff0000, 0xdb7093, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xffff0000, 0xdb7093, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xffff0000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff1493, 0xff1493, 0xff1493, 0xdb7093, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xdb7093, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xdb7093, 0xdb7093, 0xff1493, 0xff1493, 0xffff0000, 0xff1493, 0xff1493, 0xdb7093, 0xdb7093, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xdb7093, 0xdb7093, 0xffff0000, 0xff000000, 0xff000000, 0xffff0000, 0xdb7093, 0xdb7093, 0xdb7093, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xaaaaaaaa, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
};

unsigned dropping_kirby_right_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_DARK_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_DARK_PINK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_HOT_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_RED, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_RED, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_HOT_PINK, GL_LIGHT_PINK, GL_RED, GL_HOT_PINK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_PINK,GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_HOT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_BLACK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_RED, GL_LIGHT_PINK, GL_RED, GL_RED, GL_RED, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_PINK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK, GL_DARK_PINK, GL_PINK, GL_RED, GL_RED, GL_RED, GL_BLACK,
    GL_BLACK, GL_LIGHT_PINK, GL_HOT_PINK, GL_RED, GL_LIGHT_RED, GL_WHITE, GL_LIGHT_RED, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_RED, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_BLACK,
    GL_BLACK, GL_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_RED, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_BLACK,
    GL_BLACK, GL_HOT_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_RED, GL_BLACK,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_RED, GL_HOT_PINK, GL_PINK, GL_PINK, GL_PINK, GL_HOT_PINK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_RED, GL_LIGHT_RED, GL_LIGHT_RED, GL_RED, GL_BLACK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_BLACK, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE
};

unsigned dropping_kirby_left_map[] = {
0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xdb7093, 0xff1493, 0xff1493, 0xdb7093, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xffff0000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff1493, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffc0cb, 0xffb6c1, 0xff1493, 0xffff0000, 0xffb6c1, 0xff1493, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffff0000, 0xffffffff, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xff000000, 0xff1493, 0xffb6c1, 0xff000000, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffc0cb, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xff000000, 0xffc0cb, 0xffb6c1, 0xff000000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xff1493, 0xffb6c1, 0xff1493, 0xff000000, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffc0cb, 0xdb7093, 0xff000000, 0xffb6c1, 0xffb6c1, 0xff000000, 0xffc0cb, 0xdb7093, 0xdb7093, 0xffff0000, 0xffff0000, 0xffff0000, 0xffff0000, 0xffb6c1, 0xffff0000, 0xff000000, 0xff000000, 0xea3c53, 0xea3c53, 0xffff0000, 0xffff0000, 0xffc0cb, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xea3c53, 0xffffffff, 0xea3c53, 0xffff0000, 0xff1493, 0xffb6c1, 0xff000000, 0xff000000, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xff1493, 0xffb6c1, 0xdb7093, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xffff0000, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xffc0cb, 0xff000000, 0xff000000, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xff1493, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xff1493, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xff1493, 0xff000000, 0xff000000, 0xffff0000, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffb6c1, 0xffff0000, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xff000000, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xff1493, 0xffc0cb, 0xffc0cb, 0xffc0cb, 0xff1493, 0xffff0000, 0xea3c53, 0xea3c53, 0xea3c53, 0xea3c53, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xffff0000, 0xffff0000, 0xffff0000, 0xff000000, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xff1493, 0xff000000, 0xffff0000, 0xea3c53, 0xea3c53, 0xffff0000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xff000000, 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
};

unsigned ghost_kirby_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_DARK_BLUE, GL_DARK_BLUE, GL_BLUE, GL_DARK_BLUE, GL_DARK_BLUE, GL_BLACK, GL_BLACK,GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_DARK_BLUE, GL_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_WHITE, GL_DARK_BLUE, GL_LIGHT_BLUE, GL_WHITE, GL_DARK_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_LIGHT_BLUE, GL_DARK_BLUE, GL_BLACK, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_BLUE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_PASTEL_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_BLUE, GL_DARK_BLUE, GL_BLUE, GL_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_BLUE, GL_DARK_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_DARK_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_BLACK,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_DARK_BLUE, GL_PASTEL_BLUE, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_BLUE, GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_PASTEL_BLUE, GL_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_BLACK, GL_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_PASTEL_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLUE, GL_BLUE, GL_DARK_BLUE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE,GL_BLACK, GL_BLACK,GL_DARK_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_PASTEL_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_LIGHT_BLUE,GL_LIGHT_BLUE, GL_LIGHT_BLUE,GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_DARK_BLUE, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_PASTEL_BLUE, GL_BLUE, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_BLUE,GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK,GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_PASTEL_BLUE, GL_LIGHT_BLUE, GL_PASTEL_BLUE, GL_BLUE,GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_PASTEL_BLUE, GL_PASTEL_BLUE,GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLUE, GL_BLACK, GL_BLACK, GL_BLUE, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,GL_WHITE,GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_BLACK,  GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,GL_WHITE,GL_WHITE
};

unsigned coin_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_WHITE, GL_WHITE, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_ORANGE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_WHITE, GL_ORANGE, GL_YELLOW, GL_WHITE, GL_WHITE, GL_WHITE, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_YELLOW, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_AMBER, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_BLACK, GL_WHITE, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_WHITE, GL_AMBER, GL_AMBER, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_AMBER, GL_YELLOW, GL_YELLOW, GL_YELLOW, GL_BLACK, GL_BLACK, GL_YELLOW, GL_AMBER, GL_ORANGE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_AMBER, GL_ORANGE, GL_ORANGE, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_ORANGE, GL_ORANGE, GL_ORANGE, GL_ORANGE, GL_ORANGE, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE
};

unsigned gumba_leftfoot_map[] = {
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BROWN, GL_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_TAN, GL_BLACK, GL_BROWN, GL_BROWN, GL_BLACK, GL_TAN, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BROWN, GL_TAN, GL_TAN, GL_BLACK, GL_BLACK, GL_TAN, GL_TAN, GL_BROWN, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_BROWN, GL_BROWN, GL_TAN, GL_BLACK, GL_BROWN, GL_BROWN, GL_BLACK, GL_TAN, GL_BROWN, GL_BROWN, GL_BLACK, GL_BLACK, GL_WHITE,
    GL_BLACK, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_TAN, GL_BLACK, GL_BROWN, GL_BROWN, GL_BLACK, GL_TAN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BLACK,
    GL_BLACK, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN,GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BLACK,
    GL_BLACK, GL_BROWN, GL_BROWN, GL_TAN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_TAN, GL_BROWN, GL_BROWN, GL_BLACK,
    GL_WHITE, GL_BLACK, GL_BROWN, GL_TAN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_TAN, GL_BROWN, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE,
    GL_WHITE, GL_WHITE, GL_WHITE, GL_BLACK, GL_BROWN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE,
    GL_WHITE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BROWN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BROWN, GL_BLACK,
    GL_BLACK, GL_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BROWN, GL_BROWN, GL_BROWN, GL_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK,
    GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE, GL_WHITE
};

unsigned brick_map[] = {
    GL_DARK_BROWN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK, GL_DARK_BROWN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_DARK_BROWN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_TAN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_TAN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_TAN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_BLACK, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_TAN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_DARK_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_DARK_BROWN,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK,
    GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK,
    GL_BLACK, GL_BLACK, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN, GL_BLACK,
    GL_TAN, GL_TAN, GL_BLACK, GL_BLACK, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_BLACK, GL_TAN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN, GL_BLACK,
    GL_TAN, GL_DARK_BROWN, GL_TAN, GL_TAN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_TAN,GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK,
    GL_TAN,GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_TAN, GL_TAN, GL_TAN, GL_BLACK, GL_TAN,GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK,
    GL_TAN,GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN, GL_DARK_BROWN, GL_BLACK, GL_TAN,GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN, GL_DARK_BROWN,GL_DARK_BROWN,GL_BLACK, GL_BLACK,
    GL_DARK_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_DARK_BROWN, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_DARK_BROWN
};

unsigned blue_kirby_map[] = {
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_BLACK, GL_RED, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK, GL_BLACK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK,GL_BLACK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_DARK_PINK, GL_LIGHT_PINK, GL_RED, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_WHITE, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_LIGHT_PINK, GL_RED, GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_BLACK, GL_DARK_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK, GL_LIGHT_PINK, GL_DARK_PINK, GL_BLACK,GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK, GL_BLACK, GL_PASTEL_BLUE,
    GL_BLACK, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_PINK, GL_BLACK, GL_LIGHT_PINK, GL_PINK, GL_BLACK, GL_HOT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_BLACK,
    GL_BLACK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_BLACK,
    GL_BLACK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_PINK, GL_BLACK,
    GL_BLACK, GL_RED, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_DARK_PINK, GL_DARK_PINK, GL_RED, GL_BLACK,
    GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK,GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_RED, GL_RED, GL_BLACK, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_RED, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_LIGHT_PINK, GL_PINK, GL_PINK, GL_PINK, GL_RED, GL_RED, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE,
    GL_PASTEL_BLUE, GL_BLACK, GL_HOT_PINK, GL_PASTEL_BLUE, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_PINK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_BLACK, GL_PASTEL_BLUE,
    GL_BLACK, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_DARK_PINK, GL_PINK, GL_PINK, GL_PINK, GL_DARK_PINK, GL_RED, GL_RED, GL_HOT_PINK, GL_HOT_PINK, GL_HOT_PINK, GL_RED, GL_BLACK,
    GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK, GL_BLACK, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_RED, GL_BLACK,
    GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_PASTEL_BLUE, GL_PASTEL_BLUE, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_BLACK, GL_PASTEL_BLUE
};


#endif /* kirby_h */
